<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Import Condition="Exists('TargetDirectories.targets')" Project="TargetDirectories.targets"/>

    <ItemGroup>
        <ReferencesToCopy Include="..\References\IncludeInBuild\*.dll"/> 
    </ItemGroup> 
    
    <Target Condition="Exists('..\TargetDirectories.targets')" Name="CopyBuildReferences" AfterTargets="Build">
        <Copy SourceFiles="@(ReferencesToCopy)" DestinationFolder="$(ModDir)"/>
    </Target>

    <Target Condition="Exists('..\TargetDirectories.targets')" Name="CopyAssetsFromUnity" AfterTargets="Build">
        <Copy SourceFiles="..\..\SubnauticaWorldEditorAssets\Assets" DestinationFolder="$(ModDir)"/>
    </Target>
</Project>
